In [25]:
import pandas as pd

In [26]:
s  = pd.Series([1,2,3,4,5])
print(s)
print(type(s))


#ACCESSING

#indexing

print(s[0])
print(s[3])
s[0] =100

print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
4
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [27]:


s = pd.Series([23,34,25],index=["alex" , "bob" , "charlie"])
print(s)


#ACCESSING

#labels

print(s["alex"])

print(s.index)

alex       23
bob        34
charlie    25
dtype: int64
23
Index(['alex', 'bob', 'charlie'], dtype='object')

In [28]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s1+s2)


changed_s1 = s1.dr op(0)
print(s1)
print(changed_s1)

SyntaxError: invalid syntax (4027814752.py, line 6)

In [29]:
#Creating dataframes through 

#Dictonaries

info = {
    "Name" : ["alice" , "bob" , "charlie"],
    "Age" : [12,23,34],
    "CGPA" : [9.1,2.3,9.9]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

      Name  Age  CGPA
0    alice   12   9.1
1      bob   23   2.3
2  charlie   34   9.9
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [30]:

#Lists

df = pd.DataFrame([["Alice" , 23] ,["Bob" , 32] ,["Eve" , 43]] , columns=["Name" ,"Age"])
print(df)

    Name  Age
0  Alice   23
1    Bob   32
2    Eve   43

In [31]:
# Creating dataframes from numpy array

import numpy as np

np_arr = np.array([[1,2,3] , [4,5,6]])

df = pd.DataFrame(np_arr , columns=["a" , "b" , "c"])

print(df)

   a  b  c
0  1  2  3
1  4  5  6

In [32]:
 #csv data


df = pd.read_csv("employee_data.csv")
print(df , type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [33]:
#json data

df = pd.read_json("employee_data.json")
print(df , type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [34]:
# Methods
df.head() # return starting 5 row
df.tail(2) #trailing 5 values
df.sample() #gives random row
df.info() #gives random summary / information
df.shape #returns the tuple

df.describe()
df.columns
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [35]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [36]:
#AQI dataset

df = pd.read_csv("globalAirQuality.csv")

df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [37]:
df.tail()
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [38]:
#SELECTING DATA 
#selecting column

df["city"]
df[["city" ,"aqi"]]


#selecting rows


df.loc[0]
df.loc[3]

df.loc[0:2] #(0,1,2) #ending index is inclusive


df.iloc[0:2] #(0,1) #ending index is exlusive



#selecting rows and columns
df.loc[0,["pm25","city"]]
df.columns

df.iloc[0:2 , 1:5]





#cell

df.at[0, "city"] #[row,column]-> labelled
df.iat[0,2] #[row,column]-> indeexed

'New York'

In [39]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [40]:
#Filtering of data

df[df["aqi"] > 100 ]
df[(df["aqi"] > 100 ) & (df["temperature"] > 30 )]


aqi_data = df[(df["aqi"] > 100 )& (df["temperature" ] > 30)][["city" , "aqi"]]
aqi_data.iloc(0)

aqi_data

aqi_data.loc[6]




# Query method - returns copy


aqi_data = df.query("aqi >100 & temperature > 30")[["city"]].copy()

In [41]:
aqi_data

           city
6      New York
7      New York
14     New York
17     New York
25     New York
...         ...
17947    Zurich
17950    Zurich
17975    Zurich
17976    Zurich
17991    Zurich

[2384 rows x 1 columns]

In [65]:
# Cleaning data 

#handle missing value


df = pd.read_csv("raw_data.csv")


df.isnull() 


df.isna()


df.isnull().sum()


df.dropna()  #drops row


df.dropna(axis= 1) # drops column 


df.fillna(0)

age_mean = df["age"].mean()


cleaned_data = df.copy()

cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

df.ffill()

df.bfill()





#

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [76]:
#handle the duplicates




df[["country" , "gender"]].duplicated()
df2 = df.copy()

df.drop_duplicates(inplace=True)

In [106]:
# Data Types

df.dtypes 


df2 = df.copy()

df2 =df2.fillna(0)

df2["age"]= df2["age"].astype("int64").copy()


df2.dtypes



df["gender"].str.capitalize()


df["name"].str.split(" ")


df["country"].str.contains("India", case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [96]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"].dtypes

dtype('O')

In [94]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [140]:
# feature engineering 

df2 = df.copy()

df2 =df2.fillna(0)
# APPLY()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%" )




#MAP()
gender_map = {"Male" : "M" , "Female" : "F" , "Unknown" : "U"}

df2["gender"] = df2["gender"].map(gender_map)



#ASSIGN()

df2.assign(new_income = df2["income"] * 1.1)



#REPLACE ( old , new  )

df2["country"].replace("USA", "US")


# RENAME

df2.columns = ["Id" , "Name" , "Age" , "Country" , "Gender" , "Income" , "Tax"]
df2.rename(columns={"Income" :"Salary"})


df.rename(index={1:"first"})

df2["Income"].sort_values()

df2.sort_values("Income")

df2.sort_values(["Income" , "Age"])

    Id          Name   Age Country Gender   Income  Tax
4    4  Maria Garcia  34.0   Spain      F      0.0  10%
9    9   Carlos Ruiz   0.0  Mexico      M  45000.0  10%
3    3          Alex   0.0     USA      U  47000.0  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
0    1      John Doe  29.0     USA      M  55000.0  20%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%
2    2    Jane Smith   0.0  Canada      F  62000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
7    7    Ahmed Khan  38.0       0      M  68000.0  20%
6    6             0  45.0   India      F  73000.0  20%

In [ ]:
df2 =

In [111]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0